### ISSUE TITLE
Elements and workflows in the manual need to be updated to reflect new GUI

### ISSUE THREAD

**Issue by DrDap** [qsimulate/QSP_Materials_Documenation#10]
The workflows and panels described in the manual reflect the previous version, and most are going to need to be modifed/updated to reflect the changes that have been implemented with the new GUI

**Comment by spheex** [comment]
I've started working on that (branch qsp_interface).

Instead of having multiple sub-titles with the workspaces, projects and batch, I created a single section explaining briefly how it works and what it looks like (QSP Materials Interface). The 'Home' button does not work properly it seems (just go to the top of the page). And 'Feedback' redirects to a jsr webpage.

I also added detailed information in 'Workspaces, Projects & Batch'.

For the batch, I created a new page with the new GUI. However, compared to the previous GUI, I do not see conformer vs. structure calculation?

I do not know exactly how the current workflow works, so this should be explained.

Do the exploratory and rigorous types only differ by the basis set?
I do not see options for the solvation model in the advanced section of the new platform?

**Comment by Samthos** [comment]
The source for the current manual is derived from a product that performs conformer generation on a metal-ligand complex. The client that we delivered this to request upload file format was gaussian input files. 

The build of the current platform performs generation organic (like) molecules starting from smiles strings. 

There are some difference in UI between the two workflows. On the backend they are high similar.

**Comment by spheex** [comment]
In the MM filtering, which force field is used?

**Comment by Samthos** [comment]
gfn-ff or uhf.

**Comment by DrDap** [comment]
Finished and PTM.
